version: '3'

services:
    grec:
        container_name: grec
        build: .
        deploy:
            resources:
              reservations:
                devices:
                - driver: nvidia
                  count: all
                  capabilities: [gpu]
        volumes:
            - /media/data/kien/deeplib/:/app
        tty: true


